// People tagged by name alone, with no title or credit anywhere in the catalog to learn them from
// ("jelaine bagos"), so tags.ts keeps them out of the topics. Curated from the candidates that
// scripts/text/people-candidates.mjs prints; a name matches whatever its case or punctuation.
export const PEOPLE: readonly string[] = [
  'abdel jamal disangcopan',
  'abigail thea canuto',
  'Ada Angeles',
  'Adjani Arumpac',
  'Agnes Rola',
  'Aimee Dupo',
  'Aimee Lynn Barrion-Dupo',
  'alainna congjuico',
  'alfred krip yuson',
  'alfred yuson',
  'allan alvarez',
  'alona lorica',
  'Amiel Catindig',
  'andrea pasion-flores',
  'angel ouano',
  'anna tuazon',
  'apolonio chua',
  'Arlane Menor',
  'Arnald Pagulayan',
  'Arnel Casanova',
  'Arnel Salvador',
  'Arturo Pacho',
  'Atwi Suparman',
  'badette albino',
  'bambi pineda',
  'Belen Medina',
  'benedicto bacani',
  'benito pacheco',
  'bernadette espino',
  'betina evio',
  'blesilda calub',
  'Blisilda Calub',
  'Bobby Villagracia',
  'bonifacio pahowelas',
  'carlo francisco manatad',
  'cecilia panadero',
  'Celso Bejec',
  'charlotte chiong',
  'che tagyamon',
  'Chito Patiño',
  'chris millado',
  'christian monsod',
  'Christine Goma',
  'Chun-kuei Peng',
  'David Jonathan Gross',
  'Deborah Gustafson',
  'delia albert',
  'Dexter Iglesias',
  'Diane Guendin',
  'digna narvacan',
  'Doris Wilson',
  'Edison Liu',
  'Edith Tiempo',
  'edna luisa matienzo',
  'edre olalia',
  'Edsel Uy',
  'efren abueg',
  'eileen legaspi-ramirez',
  'elenita que',
  'Ericson Acosta',
  'Erma Tidon',
  'ervin temporal',
  'esmerita rotor',
  'Florangel Rosario-Braid',
  'Franchesca Casauay',
  'Gary Granada',
  'Gilda Cordero-Fernando',
  'glenn barit',
  'Gonzalo Campoamore',
  'Gonzalo Serafica',
  'Imelda Cajipe Endaya',
  'Isabel Quesada',
  'Isagani Bagus',
  'jedd chris dumaguina',
  'jeffrey camarse',
  'jelaine bagos',
  'jenifer wong',
  'Jeri Gunderson',
  'jhayle meer',
  'Jia Rubio-Monserrat',
  'Jimmie Neil Kang',
  'joanne cesario',
  'joaquin valdez',
  'joel adorada',
  'joselito florendo',
  'Josephine Dionisio',
  'Joycie Dorado Alegre',
  'juan carlos ojano',
  'kathleen lei limayo',
  'Keri Yan',
  'Laura Czerniewicz',
  'leo cubillan',
  'leonardo rosete',
  'Leonor Orosa-Goquingco',
  'loinda baldrias',
  'Lorraine Evangelista',
  'Luna Sicat-Cleto',
  'Macli-ing Dulag',
  'malou barrameda',
  'manuel donde',
  'maria karina bolasco',
  'maria ofelia liaño',
  'marie grace govez',
  'mary anne velas-suarin',
  'Mayette Bayuga',
  'Mellisa Withers',
  'Merlita Opena',
  'michael tee',
  'Mohammad Reevany Bustami',
  'myrtle sarrosa',
  'nanay mameng',
  'Noelle Polack',
  'ofelia montallana-orcales',
  'perci cendana',
  'raf dionisio',
  'Reina Olivar',
  'richard bawden',
  'Rick Baldoz',
  'rogelio mangahas',
  'roland tolentino',
  'sam manacsa',
  'Virgilio Almario',
]
